name: Deploy Blog Application
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-frontend.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GOOGLECLOUD_SERVICE_ACCOUNT }}
          credentials_json: ${{ secrets.GOOGLECLOUD_CREDENTIALS }}
      
      - name: Set image tag
        id: image_tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          no-cache: true
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:${{ steps.image_tag.outputs.TAG }}
      - id: deploy-backend
        name: Deploy backend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: blog-backend
          # image: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest
          image: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:${{ steps.image_tag.outputs.TAG }}
          region: ${{ secrets.GOOGLECLOUD_REGION }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:${{ steps.image_tag.outputs.TAG }}
          build-args: VITE_BACKEND_URL=${{ steps.deploy-backend.outputs.url }}/api/v1
      - id: deploy-frontend
        name: Deploy frontend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: blog-frontend
          # image: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest
          image: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:${{ steps.image_tag.outputs.TAG }}
          region: ${{ secrets.GOOGLECLOUD_REGION }}
